server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-cursos
          uri: lb://MS-CURSOS
          predicates:
            - Path=/api/cursos/**
          filters:
            - StripPrefix=1
        - id: ms-alumnos
          uri: lb://MS-ALUMNOS
          predicates:
            - Path=/api/alumnos/**
          filters:
            - StripPrefix=1
        - id: ms-administracion
          uri: lb://MS-ADMINISTRACION
          predicates:
            - Path=/api/administracion/**
          filters:
            - StripPrefix=1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: alpha
    tagsSorter: alpha
    urls:
      - name: ms-alumnos
        url: /api/alumnos/v3/api-docs
      - name: ms-cursos
        url: /api/cursos/v3/api-docs
      - name: ms-administracion
        url: /api/administracion/v3/api-docs
  enable-native-support: true
  api-docs:
    enabled: true
